# alacritty.yml
# Config file for Alacritty
# Located in ~/.config

font:
    normal:
        family: Meslo LG M DZ
        style: Regular
    
    bold:
        family: Meslo LG M DZ
        style: Bold
    
    italic:
        family: Meslo LG M DZ
        style: Italic
    
    bold_italic:
        family: Meslo LG M DZ
        style: Bold Italic

colors:
    primary:
        background: '0x1d2021'
        foreground: '0xebdbb2'
    
    selection:
        text: '0xfbf1c7'
        background: '0x282828'
    
    normal:
        black: '0x1d2021'
        red: '0xcc241d'
        green: '0x98971a'
        yellow: '0xd79921'
        blue: '0x458588'
        magenta: '0xb16286'
        cyan: '0x689d6a'
        white: '0xa89984'
    
    bright:
        black: '0x928374'
        red: '0xfb4934'
        green: '0xb8bb26'
        yellow: '0xfabd2f'
        blue: '0x83a598'
        magenta: '0xd3869b'
        cyan: '0x8ec07c'
        white: '0xebdbb2'

#window:
#    opacity: 0.90

live_config_reload: true

mouse_bindings:
    - { mouse: Middle,  action: PasteSelection }

key_bindings:
    - { key: C,         mods: Control|Shift,  action: Copy             }
    - { key: V,         mods: Control|Shift,  action: Paste            }
    - { key: Equals,    mods: Control,        action: IncreaseFontSize }
    - { key: Minus,     mods: Control,        action: DecreaseFontSize }
    - { key: Key0,      mods: Control,        action: ResetFontSize    }
    - { key: PageUp,    mods: Control,        action: ScrollPageUp     }
    - { key: PageDown,  mods: Control,        action: ScrollPageDown   }
    - { key: Up,        mods: Control,        action: ScrollLineUp     }
    - { key: Down,      mods: Control,        action: ScrollLineDown   }
    - { key: Home,      mods: Control,        action: ScrollToTop      }
    - { key: End,       mods: Control,        action: ScrollToBottom   }
    - { key: L,         mods: Control,        chars: "\x0c"            }
