#!/usr/bin/env sh
# Config file for bspwm
# Located in ~/.config/bspwm

# Launch or relaunch daemons
pkill -x sxhkd; sxhkd &
pkill -x dunst; dunst &
pgrep -x picom > /dev/null || picom &

# Configure cursor
xsetroot -cursor_name left_ptr
xset r rate 200 50
bspc config pointer_motion_interval 10

# Configure gaps
bspc config border_width          2
bspc config window_gap            7

# Configure windows
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

# Configure application rules
bspc rule -a albert               border=off
bspc rule -a feh                  state=floating
bspc rule -a Zathura              state=tiled

# Configure machine specific settings
case "$(cat /etc/hostname)" in
	('jupiter')
		pkill -x polybar; polybar b0 & polybar b1 &
		pgrep -x numlockx > /dev/null || numlockx &
		
		bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 0 - =
		bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0 - =
		;;
	(*)
		pkill -x polybar; polybar b0 &
		pkill -x nm-applet; nm-applet &
		
		bspc monitor -d 1 2 3 4 5 6 7 8 9 0 - =
		;;
esac
