#!/usr/bin/env sh
# reflac, version 0.2.0
# Shell script for (re)encoding FLAC files

# Print the message $1 to stderr and potentiall exit.
error() { echo "$(basename "$0"): $1" >&2; exit 1; }
warn() { echo "$(basename "$0"): $1" >&2; }

# Check that FLAC is installed
if ! command -v flac > /dev/null; then error 'flac: Not found in PATH'; fi

FLAC_OPTIONS='-8 --replay-gain -f'

# (Re)encode each argument as a FLAC file or folder containing FLAC files
for a in "$@"; do
	# If the argument is a file, then (re)encode it on its own
	if [ -f "$a" ]; then flac $FLAC_OPTIONS -- "$a"; continue; fi
	
	# If the argument is a directory, then (re)encode the directory together
	if [ -d "$a" ]; then
		for f in "$a"/*.flac; do FLAC_FILES="$FLAC_FILES\"$f\" "; done
		eval flac $FLAC_OPTIONS -- $FLAC_FILES; continue
	fi
	
	warn "$a: No such file or directory";
done
