#!/usr/bin/env sh
# sudo, version 0.2.0
# Shell script Sudo wrapper for OpenDoas

# Print the message $1 to stderr and potentially exit.
error() { echo "$(basename "$0"): $1" >&2; exit 1; }
warn() { echo "$(basename "$0"): $1" >&2; }

# Ensure that required programs are installed
if ! command -v doas > /dev/null; then error 'doas: Not found in PATH'; fi

# Parse arguments
ARGS=$(getopt -o '+E' -- "$@") || exit 1; eval "set -- $ARGS"

while true; do case $1 in
	(-E) EFLAG=true; shift 1;;
	(--) shift 1; break;;
	(*)  exit 1;;
esac done

if [ "$EFLAG" = true ]; then SH_COMMAND="$SH_COMMAND export '$(env)';"; fi

for a in "$@"; do DOAS_COMMAND="$DOAS_COMMAND '$a'"; done

# Execute generated doas command
doas $DOAS_OPTIONS -- sh -c "$SH_COMMAND $DOAS_COMMAND"
